import '../css/app.css';
import {createInertiaApp,Link,router,usePage} from '@inertiajs/react';
import {createRoot} from 'react-dom/client';
import {useState} from 'react';
const nav={admin:[['Dashboard','/admin','bi-grid'],['Employees','/admin/employees','bi-people'],['Departments & Positions','/admin/departments','bi-building'],['Attendance','/admin/attendance','bi-clock'],['Salary Processing','/admin/payroll','bi-cash-stack'],['Attendance Report','/reports/attendance','bi-file-earmark-text'],['Payroll Report','/reports/payroll','bi-file-earmark-bar-graph'],['Employee List','/reports/employees','bi-person-vcard']],employee:[['Dashboard','/employee','bi-grid'],['Attendance History','/employee/attendance','bi-clock-history'],['Payroll History','/employee/payroll','bi-wallet2'],['My Profile','/employee/profile','bi-person-badge']]};
export function Shell({children,title}){const {auth}=usePage().props;const role=auth.user.role;return <div className="sh-shell"><aside className="sh-sidebar"><div className="sh-brand"><div className="sh-brand-mark"><img src="/logo%20wo%20text.png" alt="StaffHub"/></div><div><div className="sh-brand-wordmark">StaffHub</div><small>{role==='admin'?'Admin Console':'Employee Portal'}</small></div></div><nav className="sh-nav">{nav[role].map(([label,url,icon])=><Link key={url} href={url} className={'sh-nav-link '+(location.pathname===url?'active':'')}><i className={'bi '+icon}/><span>{label}</span></Link>)}</nav><button className="sh-nav-link border-0 bg-transparent text-start" onClick={()=>router.post('/logout')}><i className="bi bi-box-arrow-right"/><span>Logout</span></button></aside><main className="sh-main"><div className="sh-topbar"><h5 className="m-0">{title}</h5><div className="sh-avatar">{auth.user.name?.slice(0,1)||auth.user.username.slice(0,1)}</div></div><div className="sh-content">{children}</div></main></div>}
function Table({rows,columns}){return <div className="table-responsive"><table className="table align-middle"><thead><tr>{columns.map(c=><th key={c[0]}>{c[0]}</th>)}</tr></thead><tbody>{rows?.length?rows.map((row,i)=><tr key={row.employee_id||row.attendance_id||row.payroll_id||i}>{columns.map(([_,key])=><td key={key}>{typeof key==='function'?key(row):row[key]??'—'}</td>)}</tr>):<tr><td colSpan={columns.length} className="text-center text-muted py-4">No records found.</td></tr>}</tbody></table></div>}
function Login(){const {errors}=usePage().props;const [data,setData]=useState({username:'',password:''});return <main className="sh-login-page"><form className="sh-login-card" onSubmit={e=>{e.preventDefault();router.post('/login',data)}}><img src="/logo%20wo%20text.png" className="sh-login-logo"/><h1>Welcome back</h1><p>Sign in to StaffHub</p><input className="form-control mb-3" placeholder="Username" value={data.username} onChange={e=>setData({...data,username:e.target.value})}/><input className="form-control mb-3" type="password" placeholder="Password" value={data.password} onChange={e=>setData({...data,password:e.target.value})}/>{errors.username&&<div className="alert alert-danger">{errors.username}</div>}<button className="btn btn-primary w-100">Sign in</button></form></main>}
function Dashboard({stats,activities,employee,today,history,lastPayroll}){const employeeMode=!!employee;return <Shell title={employeeMode?'My Dashboard':'Dashboard'}><div className="sh-page-header"><div><h1>{employeeMode?`Hello, ${employee.first_name}`:'Workforce overview'}</h1><p>{employeeMode?'Your time and payroll at a glance.':'Monitor your team in real time.'}</p></div></div>{employeeMode?<><div className="row g-3 mb-4"><div className="col-md-4"><div className="sh-stat-card"><span>Today</span><strong>{today?.status||'Not clocked in'}</strong></div></div><div className="col-md-4"><div className="sh-stat-card"><span>Last payroll</span><strong>₱{lastPayroll?.net_salary||'0.00'}</strong></div></div></div><Table rows={history} columns={[["Date",r=>r.attendance_date?.slice(0,10)],["Hours",'total_hours'],['Status','status']]}/></>:<><div className="row g-3 mb-4">{Object.entries(stats).map(([k,v])=><div className="col-sm-6 col-xl-3" key={k}><div className="sh-stat-card"><span>{k.replaceAll('_',' ')}</span><strong>{v}</strong></div></div>)}</div><Table rows={activities} columns={[["Activity",'activity'],['When',r=>r.timestamp?.slice(0,16)]]}/></>}</Shell>}
function Employees({employees,departments,positions}){return <Shell title="Employee Management"><div className="sh-page-header"><div><h1>Employees</h1><p>Manage staff records and accounts.</p></div></div><Table rows={employees.data} columns={[["Code",'employee_code'],['Employee','full_name'],['Department',r=>r.department?.department_name],['Position',r=>r.position?.position_name],['Status',r=>r.is_active?'Active':'Inactive']]}/></Shell>}
function Records({title,rows,type}){const cols=type==='attendance'?[["Date",r=>r.attendance_date?.slice(0,10)],["Employee",r=>r.employee?.full_name],["Hours",'total_hours'],['Status','status']]:type==='payroll'?[["Employee",r=>r.employee?.full_name],["Period",r=>`${r.payroll_period_start?.slice(0,10)} – ${r.payroll_period_end?.slice(0,10)}`],["Net salary",r=>`₱${r.net_salary}`]]:[["Code",'employee_code'],['Employee','full_name'],['Department',r=>r.department?.department_name],['Status',r=>r.is_active?'Active':'Inactive']];return <Shell title={title}><div className="sh-page-header"><div><h1>{title}</h1></div><button className="btn btn-outline-secondary" onClick={()=>print()}>Print</button></div><Table rows={rows.data||rows} columns={cols}/></Shell>}
function Organization({departments,positions}){return <Shell title="Departments & Positions"><h1>Departments & Positions</h1><div className="row"><div className="col-md-6"><h5>Departments</h5><Table rows={departments} columns={[["Name",'department_name'],['Description','description']]}/></div><div className="col-md-6"><h5>Positions</h5><Table rows={positions} columns={[["Position",'position_name'],['Department',r=>r.department?.department_name]]}/></div></div></Shell>}
function Profile({employee}){return <Shell title="My Profile"><h1>My Profile</h1><div className="card p-4"><dl className="row mb-0"><dt className="col-sm-3">Employee ID</dt><dd className="col-sm-9">{employee.employee_code}</dd><dt className="col-sm-3">Name</dt><dd className="col-sm-9">{employee.full_name}</dd><dt className="col-sm-3">Email</dt><dd className="col-sm-9">{employee.email}</dd><dt className="col-sm-3">Department</dt><dd className="col-sm-9">{employee.department?.department_name}</dd></dl></div></Shell>}
const pages={ 'Auth/Login':Login,'Admin/Dashboard':Dashboard,'Admin/Employees':Employees,'Admin/Organization':Organization,'Admin/Attendance':p=><Records title="Attendance" rows={p.attendance} type="attendance"/>,'Admin/Payroll':p=><Records title="Salary Processing" rows={p.payrolls} type="payroll"/>,'Employee/Dashboard':Dashboard,'Employee/Attendance':p=><Records title="Attendance History" rows={p.attendance} type="attendance"/>,'Employee/Payroll':p=><Records title="Payroll History" rows={p.payrolls} type="payroll"/>,'Employee/Profile':Profile,'Reports/Index':p=><Records title={`${p.type[0].toUpperCase()+p.type.slice(1)} Report`} rows={p.rows} type={p.type==='employees'?'employees':p.type}/>};
createInertiaApp({resolve:name=>pages[name],setup:({el,App,props})=>createRoot(el).render(<App {...props}/>) });
