import { Link, router, usePage } from '@inertiajs/react';
import { createRoot } from 'react-dom/client';
import { useState } from 'react';

const adminNav = [['Dashboard','/admin'],['Employees','/admin/employees'],['Organization','/admin/organization'],['Attendance','/admin/attendance'],['Payroll','/admin/payroll']];
const employeeNav = [['Dashboard','/employee'],['Attendance','/employee/attendance'],['Payroll','/employee/payroll'],['Profile','/employee/profile']];
const shortDate = (value) => value ? String(value).slice(0, 10) : '—';

function Field({label, error, ...input}) { return <label className="d-grid gap-1 mb-3"><span className="small fw-semibold">{label}</span><input className="form-control" {...input}/>{error && <small className="text-danger">{error}</small>}</label>; }
export function Auth({kind}) {
 const page=usePage(); const errors=page.props.errors; const [data,setData]=useState(kind==='register'?{first_name:'',last_name:'',username:'',email:'',password:'',password_confirmation:''}:kind==='reset'?{email:page.props.email||'',token:page.props.token||'',password:'',password_confirmation:''}:{email:'',password:''});
 const change=(key)=>(e)=>setData({...data,[key]:e.target.value});
 const submit=(e)=>{e.preventDefault();router.post(kind==='login'?'/login':kind==='register'?'/register':kind==='forgot'?'/forgot-password':'/reset-password',data);};
 return <main className="sh-login-page"><form className="sh-login-card" onSubmit={submit}><img src="/logo%20wo%20text.png" className="sh-login-logo" alt="StaffHub"/><h1>{kind==='login'?'Welcome back':kind==='register'?'Create employee account':kind==='forgot'?'Forgot password':'Reset password'}</h1>{kind==='register'&&<><Field label="First name" value={data.first_name} onChange={change('first_name')} error={errors.first_name} required/><Field label="Last name" value={data.last_name} onChange={change('last_name')} error={errors.last_name} required/><Field label="Username" value={data.username} onChange={change('username')} error={errors.username} required/></>}<Field label="Email" type="email" value={data.email} onChange={change('email')} error={errors.email} required/>{kind!=='forgot'&&<><Field label="Password" type="password" value={data.password} onChange={change('password')} error={errors.password} required/><Field label="Confirm password" type="password" value={data.password_confirmation||''} onChange={change('password_confirmation')} required/></>}<button className="btn btn-primary w-100">{kind==='login'?'Sign in':kind==='forgot'?'Email reset link':kind==='reset'?'Reset password':'Register'}</button>{kind==='login'?<p className="small mt-3 d-flex justify-content-between"><Link href="/forgot-password">Forgot password?</Link><Link href="/register">Register</Link></p>:<Link href="/login" className="small d-block mt-3">Back to sign in</Link>}</form></main>;
}
function Shell({title,children}) {
 const page=usePage(); const user=page.props.auth.user; const [open,setOpen]=useState(false); const admin=user.roles.includes('Admin'); const nav=admin?adminNav:employeeNav;
 return <div className="sh-shell"><aside className={'sh-sidebar '+(open?'open':'')}><div className="sh-brand"><img src="/logo%20wo%20text.png" alt="StaffHub"/><span>StaffHub</span></div><nav className="sh-nav">{nav.map(([label,href])=><Link key={href} className={'sh-nav-link '+(location.pathname===href?'active':'')} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<button className="sh-nav-link border-0 bg-transparent text-start" onClick={()=>router.post('/logout')}>Logout</button></nav></aside><main className="sh-main"><header className="sh-topbar"><button className="btn btn-outline-secondary d-md-none" onClick={()=>setOpen(!open)}>Menu</button><h5>{title}</h5><small>{user.name}</small></header><section className="sh-content">{page.props.flash.success&&<div className="alert alert-success">{page.props.flash.success}</div>}{children}</section></main></div>;
}
function Table({rows,columns,actions}) { return <div className="table-responsive"><table className="table align-middle"><thead><tr>{columns.map(c=><th key={c[0]}>{c[0]}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{rows?.length?rows.map((row,index)=><tr key={row.employee_id||row.department_id||row.position_id||row.attendance_id||row.payroll_id||index}>{columns.map(c=><td key={c[0]}>{typeof c[1]==='function'?c[1](row):row[c[1]]||'—'}</td>)}{actions&&<td>{actions(row)}</td>}</tr>):<tr><td colSpan={columns.length+(actions?1:0)} className="text-center text-muted py-4">No records found.</td></tr>}</tbody></table></div>; }
function Pagination({data}) { return data?.links&&<nav><ul className="pagination">{data.links.map((link,index)=><li key={index} className={'page-item '+(link.active?'active ':'')+(link.url?'':'disabled')}><button className="page-link" disabled={!link.url} onClick={()=>link.url&&router.get(link.url)} dangerouslySetInnerHTML={{__html:link.label}}/></li>)}</ul></nav>; }
export function Dashboard(props) { const employee=props.employee; return <Shell title="Dashboard"><h1 className="h3 mb-4">{employee?'Hello, '+employee.first_name:'Workforce overview'}</h1>{employee?<><div className="btn-group mb-4"><button className="btn btn-primary" onClick={()=>router.post('/employee/attendance/in')}>Clock in</button><button className="btn btn-outline-primary" onClick={()=>router.post('/employee/attendance/out')}>Clock out</button></div><Table rows={props.history} columns={[["Date",r=>shortDate(r.attendance_date)],['Hours','total_hours'],['Status','status']]}/></>:<div className="row g-3">{Object.entries(props.stats).map(([name,value])=><div className="col-sm-6 col-xl-3" key={name}><div className="sh-stat-card"><span>{name.replaceAll('_',' ')}</span><strong>{value}</strong></div></div>)}</div>}</Shell>; }
export function Employees({employees,departments,positions}) { const page=usePage(); const can=page.props.auth.user.permissions.includes('employees.manage'); const [show,setShow]=useState(false); const [d,setD]=useState({employee_code:'',username:'',first_name:'',last_name:'',email:'',password:'',password_confirmation:'',department_id:'',position_id:'',gender:'Other',birthdate:'',contact_number:'',employment_status:'Full-Time',basic_hourly_rate:'0',date_hired:new Date().toISOString().slice(0,10)}); const set=(key)=>(e)=>setD({...d,[key]:e.target.value}); return <Shell title="Employees"><div className="d-flex justify-content-between mb-3"><h1 className="h3">Employees</h1>{can&&<button className="btn btn-primary" onClick={()=>setShow(!show)}>Add employee</button>}</div>{show&&<form className="card card-body row g-2 mb-4" onSubmit={e=>{e.preventDefault();router.post('/admin/employees',d,{onSuccess:()=>setShow(false)});}}>{[['employee_code','Employee code'],['username','Username'],['first_name','First name'],['last_name','Last name'],['email','Email'],['password','Password'],['password_confirmation','Confirm password'],['birthdate','Birthdate'],['contact_number','Contact number'],['basic_hourly_rate','Hourly rate'],['date_hired','Date hired']].map(([key,label])=><div className="col-md-4" key={key}><Field label={label} type={key.includes('password')?'password':key.includes('date')?'date':key==='email'?'email':key==='basic_hourly_rate'?'number':'text'} value={d[key]} onChange={set(key)} error={page.props.errors[key]} required/></div>)}<div className="col-md-4"><select className="form-select" value={d.department_id} onChange={set('department_id')}><option value="">Department</option>{departments.map(x=><option key={x.department_id} value={x.department_id}>{x.department_name}</option>)}</select></div><div className="col-md-4"><select className="form-select" value={d.position_id} onChange={set('position_id')}><option value="">Position</option>{positions.map(x=><option key={x.position_id} value={x.position_id}>{x.position_name}</option>)}</select></div><div><button className="btn btn-primary">Save</button></div></form>}<Table rows={employees.data} columns={[['Code','employee_code'],['Employee','full_name'],['Department',r=>r.department?.department_name],['Position',r=>r.position?.position_name],['Status',r=>r.is_active?'Active':'Archived']]} actions={can?r=><button className="btn btn-sm btn-outline-danger" disabled={!r.is_active} onClick={()=>confirm('Archive employee?')&&router.delete('/admin/employees/'+r.employee_id)}>Archive</button>:null}/><Pagination data={employees}/></Shell>; }
export function Organization({departments,positions}) { const can=usePage().props.auth.user.permissions.includes('organization.manage'); const [name,setName]=useState(''); const [position,setPosition]=useState(''); return <Shell title="Organization"><h1 className="h3">Departments & positions</h1>{can&&<div className="row mb-4"><form className="col-md-6 d-flex gap-2" onSubmit={e=>{e.preventDefault();router.post('/admin/departments',{department_name:name});}}><input className="form-control" placeholder="New department" value={name} onChange={e=>setName(e.target.value)}/><button className="btn btn-primary">Add</button></form><form className="col-md-6 d-flex gap-2" onSubmit={e=>{e.preventDefault();router.post('/admin/positions',{position_name:position});}}><input className="form-control" placeholder="New position" value={position} onChange={e=>setPosition(e.target.value)}/><button className="btn btn-primary">Add</button></form></div>}<div className="row"><div className="col-md-6"><Table rows={departments} columns={[['Department','department_name'],['Description','description']]} actions={can?r=><button className="btn btn-sm btn-outline-danger" onClick={()=>router.delete('/admin/departments/'+r.department_id)}>Delete</button>:null}/></div><div className="col-md-6"><Table rows={positions} columns={[['Position','position_name'],['Department',r=>r.department?.department_name]]} actions={can?r=><button className="btn btn-sm btn-outline-danger" onClick={()=>router.delete('/admin/positions/'+r.position_id)}>Delete</button>:null}/></div></div></Shell>; }
export function Attendance({attendance,employees}) {
    const page = usePage();
    const admin = page.props.auth.user.permissions.includes('attendance.manage');
    const [showForm, setShowForm] = useState(false);
    const [data, setData] = useState({employee_id:'',attendance_date:new Date().toISOString().slice(0,10),time_in:'',time_out:'',status:'Completed'});
    const change = (key) => (event) => setData({...data,[key]:event.target.value});

    return <Shell title="Attendance"><div className="d-flex justify-content-between mb-3"><h1 className="h3">Attendance</h1>{admin ? <button className="btn btn-primary" onClick={()=>setShowForm(!showForm)}>Add record</button> : <div className="btn-group"><button className="btn btn-primary" onClick={()=>router.post('/employee/attendance/in')}>Clock in</button><button className="btn btn-outline-primary" onClick={()=>router.post('/employee/attendance/out')}>Clock out</button></div>}</div>{showForm && <form className="card card-body row g-2 mb-4" onSubmit={(event)=>{event.preventDefault();router.post('/admin/attendance',data,{onSuccess:()=>setShowForm(false)});}}><div className="col-md-4"><select className="form-select" value={data.employee_id} onChange={change('employee_id')} required><option value="">Select employee</option>{employees.map((employee)=><option key={employee.employee_id} value={employee.employee_id}>{employee.full_name}</option>)}</select></div><div className="col-md-4"><Field label="Date" type="date" value={data.attendance_date} onChange={change('attendance_date')} required/></div><div className="col-md-4"><Field label="Time in" type="datetime-local" value={data.time_in} onChange={change('time_in')}/></div><div className="col-md-4"><Field label="Time out" type="datetime-local" value={data.time_out} onChange={change('time_out')}/></div><div className="col-12"><button className="btn btn-primary">Save attendance</button></div></form>}<Table rows={attendance.data} columns={[['Date',row=>shortDate(row.attendance_date)],['Employee',row=>row.employee?.full_name],['Hours','total_hours'],['Status','status']]} actions={admin?row=><>{row.status==='Completed'&&<button className="btn btn-sm btn-outline-primary me-1" onClick={()=>router.post('/admin/attendance/'+row.attendance_id+'/verify')}>Verify</button>}<button className="btn btn-sm btn-outline-danger" onClick={()=>confirm('Delete attendance?')&&router.delete('/admin/attendance/'+row.attendance_id)}>Delete</button></>:null}/><Pagination data={attendance}/></Shell>;
}

export function Payroll({payrolls,employees}) {
    const page = usePage();
    const admin = page.props.auth.user.permissions.includes('payroll.manage');
    const [showForm, setShowForm] = useState(false);
    const [data, setData] = useState({employee_id:'',payroll_period_start:'',payroll_period_end:'',bonuses:'0',deductions:'0'});
    const change = (key) => (event) => setData({...data,[key]:event.target.value});

    return <Shell title="Payroll"><div className="d-flex justify-content-between mb-3"><h1 className="h3">Payroll</h1>{admin&&<button className="btn btn-primary" onClick={()=>setShowForm(!showForm)}>Calculate payroll</button>}</div>{showForm&&<form className="card card-body row g-2 mb-4" onSubmit={(event)=>{event.preventDefault();router.post('/admin/payroll',data,{onSuccess:()=>setShowForm(false)});}}><div className="col-md-4"><select className="form-select" value={data.employee_id} onChange={change('employee_id')} required><option value="">Select employee</option>{employees.map((employee)=><option key={employee.employee_id} value={employee.employee_id}>{employee.full_name}</option>)}</select></div><div className="col-md-4"><Field label="Period start" type="date" value={data.payroll_period_start} onChange={change('payroll_period_start')} required/></div><div className="col-md-4"><Field label="Period end" type="date" value={data.payroll_period_end} onChange={change('payroll_period_end')} required/></div><div className="col-md-4"><Field label="Bonus" type="number" value={data.bonuses} onChange={change('bonuses')}/></div><div className="col-md-4"><Field label="Deductions" type="number" value={data.deductions} onChange={change('deductions')}/></div><div className="col-12"><button className="btn btn-primary">Calculate</button></div></form>}<Table rows={payrolls.data} columns={[['Employee',row=>row.employee?.full_name],['Period',row=>shortDate(row.payroll_period_start)+' – '+shortDate(row.payroll_period_end)],['Hours','verified_hours'],['Net',row=>'₱'+row.net_salary]]} actions={admin?row=><button className="btn btn-sm btn-outline-danger" onClick={()=>confirm('Delete payroll?')&&router.delete('/admin/payroll/'+row.payroll_id)}>Delete</button>:null}/><Pagination data={payrolls}/></Shell>;
}

export function Profile({employee}) { const [d,setD]=useState({contact_number:employee.contact_number||'',address:employee.address||''}); return <Shell title="Profile"><h1 className="h3">My profile</h1><form className="card card-body col-lg-6" onSubmit={e=>{e.preventDefault();router.put('/employee/profile',d);}}><p><strong>{employee.full_name}</strong><br/>{employee.employee_code}</p><Field label="Contact number" value={d.contact_number} onChange={e=>setD({...d,contact_number:e.target.value})} required/><Field label="Address" value={d.address} onChange={e=>setD({...d,address:e.target.value})}/><button className="btn btn-primary">Update profile</button></form></Shell>; }
export function Reports({type,rows}) { return <Shell title="Reports"><button className="btn btn-outline-secondary float-end" onClick={()=>window.print()}>Print</button><h1 className="h3 text-capitalize">{type} report</h1><Table rows={rows} columns={type==='attendance'?[['Date',r=>shortDate(r.attendance_date)],['Employee',r=>r.employee?.full_name],['Hours','total_hours']]:type==='payroll'?[['Employee',r=>r.employee?.full_name],['Net','net_salary']]:[['Code','employee_code'],['Employee','full_name']]}/></Shell>; }
